// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_settings.sql

package db

import (
	"context"
)

const getRegistrationsEnabled = `-- name: GetRegistrationsEnabled :one
SELECT registrations_enabled FROM instance_settings WHERE id = 1
`

func (q *Queries) GetRegistrationsEnabled(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getRegistrationsEnabled)
	var registrations_enabled bool
	err := row.Scan(&registrations_enabled)
	return registrations_enabled, err
}

const setRegistrationsEnabled = `-- name: SetRegistrationsEnabled :exec
UPDATE instance_settings SET registrations_enabled = $1 WHERE id = 1
`

func (q *Queries) SetRegistrationsEnabled(ctx context.Context, registrationsEnabled bool) error {
	_, err := q.db.Exec(ctx, setRegistrationsEnabled, registrationsEnabled)
	return err
}
