// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at = now() WHERE token = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, acceptInvitation, token)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (email, role, token, expires_at, invited_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, role, token, expires_at, accepted_at, invited_by, created_at
`

type CreateInvitationParams struct {
	Email     string
	Role      string
	Token     string
	ExpiresAt pgtype.Timestamptz
	InvitedBy pgtype.UUID
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
		arg.InvitedBy,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, email, role, token, expires_at, accepted_at, invited_by, created_at
FROM invitations
WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, email, role, token, expires_at, accepted_at, invited_by, created_at
FROM invitations
ORDER BY created_at DESC
`

func (q *Queries) ListInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
