// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at = now() WHERE token = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, acceptInvitation, token)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (team_id, email, role, token, expires_at, invited_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, email, role, token, expires_at, accepted_at, invited_by, created_at
`

type CreateInvitationParams struct {
	TeamID    pgtype.UUID
	Email     string
	Role      string
	Token     string
	ExpiresAt pgtype.Timestamptz
	InvitedBy pgtype.UUID
}

type CreateInvitationRow struct {
	ID         pgtype.UUID
	TeamID     pgtype.UUID
	Email      string
	Role       string
	Token      string
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	InvitedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
		arg.InvitedBy,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1 AND team_id = $2
`

type DeleteInvitationParams struct {
	ID     pgtype.UUID
	TeamID pgtype.UUID
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteInvitation, arg.ID, arg.TeamID)
	return err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, team_id, email, role, token, expires_at, accepted_at, invited_by, created_at
FROM invitations
WHERE token = $1
`

type GetInvitationByTokenRow struct {
	ID         pgtype.UUID
	TeamID     pgtype.UUID
	Email      string
	Role       string
	Token      string
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	InvitedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i GetInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, team_id, email, role, token, expires_at, accepted_at, invited_by, created_at
FROM invitations
WHERE team_id = $1 AND accepted_at IS NULL
ORDER BY created_at DESC
`

type ListInvitationsRow struct {
	ID         pgtype.UUID
	TeamID     pgtype.UUID
	Email      string
	Role       string
	Token      string
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	InvitedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListInvitations(ctx context.Context, teamID pgtype.UUID) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsRow
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
