// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID         pgtype.UUID
	IncidentID pgtype.UUID
	SentAt     pgtype.Timestamptz
	AlertEmail string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type InstanceSetting struct {
	ID                   int32
	RegistrationsEnabled bool
}

type Invitation struct {
	ID         pgtype.UUID
	Email      string
	Role       string
	Token      string
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	InvitedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	TeamID     pgtype.UUID
}

type Monitor struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Url                string
	AlertEmail         pgtype.Text
	IntervalSec        int32
	TimeoutSec         int32
	LatencyThresholdMs pgtype.Int4
	ExpectedStatus     pgtype.Int4
	Enabled            bool
	UpdatedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	TeamID             pgtype.UUID
}

type MonitorIncident struct {
	ID         pgtype.UUID
	MonitorID  pgtype.UUID
	StartTime  pgtype.Timestamptz
	EndTime    pgtype.Timestamptz
	Alerted    bool
	HttpStatus int32
	LatencyMs  int32
	CreatedAt  pgtype.Timestamptz
}

type Team struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TeamMember struct {
	ID       pgtype.UUID
	TeamID   pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	IsActive bool
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Name          string
	Email         string
	PasswordHash  string
	Role          string
	MonitorsCount pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	IsActive      bool
}
