// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    user_id,
    team_id,
    url,
    interval_sec,
    timeout_sec,
    latency_threshold_ms,
    expected_status,
    alert_email
) VALUES (
             $1,
             $2,
             $3,
             $4,
             $5,
             $6,
             $7,
             $8
         )
    RETURNING id
`

type CreateMonitorParams struct {
	UserID             pgtype.UUID
	TeamID             pgtype.UUID
	Url                string
	IntervalSec        int32
	TimeoutSec         int32
	LatencyThresholdMs pgtype.Int4
	ExpectedStatus     pgtype.Int4
	AlertEmail         pgtype.Text
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.TeamID,
		arg.Url,
		arg.IntervalSec,
		arg.TimeoutSec,
		arg.LatencyThresholdMs,
		arg.ExpectedStatus,
		arg.AlertEmail,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors
WHERE id = $1 AND team_id = $2
`

type DeleteMonitorParams struct {
	ID     pgtype.UUID
	TeamID pgtype.UUID
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitor, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllMonitorsByTeamID = `-- name: GetAllMonitorsByTeamID :many
SELECT id, user_id, team_id, url, alert_email, interval_sec, timeout_sec, latency_threshold_ms, expected_status, enabled
FROM monitors
WHERE team_id = $1
ORDER BY updated_at
    LIMIT $2
OFFSET $3
`

type GetAllMonitorsByTeamIDParams struct {
	TeamID pgtype.UUID
	Limit  int32
	Offset int32
}

type GetAllMonitorsByTeamIDRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	TeamID             pgtype.UUID
	Url                string
	AlertEmail         pgtype.Text
	IntervalSec        int32
	TimeoutSec         int32
	LatencyThresholdMs pgtype.Int4
	ExpectedStatus     pgtype.Int4
	Enabled            bool
}

func (q *Queries) GetAllMonitorsByTeamID(ctx context.Context, arg GetAllMonitorsByTeamIDParams) ([]GetAllMonitorsByTeamIDRow, error) {
	rows, err := q.db.Query(ctx, getAllMonitorsByTeamID, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMonitorsByTeamIDRow
	for rows.Next() {
		var i GetAllMonitorsByTeamIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamID,
			&i.Url,
			&i.AlertEmail,
			&i.IntervalSec,
			&i.TimeoutSec,
			&i.LatencyThresholdMs,
			&i.ExpectedStatus,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, team_id, url, alert_email, interval_sec, timeout_sec, latency_threshold_ms, expected_status, enabled
FROM monitors
WHERE id = $1
`

type GetMonitorByIDRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	TeamID             pgtype.UUID
	Url                string
	AlertEmail         pgtype.Text
	IntervalSec        int32
	TimeoutSec         int32
	LatencyThresholdMs pgtype.Int4
	ExpectedStatus     pgtype.Int4
	Enabled            bool
}

func (q *Queries) GetMonitorByID(ctx context.Context, id pgtype.UUID) (GetMonitorByIDRow, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i GetMonitorByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Url,
		&i.AlertEmail,
		&i.IntervalSec,
		&i.TimeoutSec,
		&i.LatencyThresholdMs,
		&i.ExpectedStatus,
		&i.Enabled,
	)
	return i, err
}

const getMonitorByTeamID = `-- name: GetMonitorByTeamID :one
SELECT id, user_id, team_id, url, alert_email, interval_sec, timeout_sec, latency_threshold_ms, expected_status, enabled
FROM monitors
WHERE id = $1 AND team_id = $2
`

type GetMonitorByTeamIDParams struct {
	ID     pgtype.UUID
	TeamID pgtype.UUID
}

type GetMonitorByTeamIDRow struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	TeamID             pgtype.UUID
	Url                string
	AlertEmail         pgtype.Text
	IntervalSec        int32
	TimeoutSec         int32
	LatencyThresholdMs pgtype.Int4
	ExpectedStatus     pgtype.Int4
	Enabled            bool
}

func (q *Queries) GetMonitorByTeamID(ctx context.Context, arg GetMonitorByTeamIDParams) (GetMonitorByTeamIDRow, error) {
	row := q.db.QueryRow(ctx, getMonitorByTeamID, arg.ID, arg.TeamID)
	var i GetMonitorByTeamIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Url,
		&i.AlertEmail,
		&i.IntervalSec,
		&i.TimeoutSec,
		&i.LatencyThresholdMs,
		&i.ExpectedStatus,
		&i.Enabled,
	)
	return i, err
}

const updateMonitorStatus = `-- name: UpdateMonitorStatus :execrows
UPDATE monitors
SET enabled = $2
WHERE id = $1 AND team_id = $3
`

type UpdateMonitorStatusParams struct {
	ID      pgtype.UUID
	Enabled bool
	TeamID  pgtype.UUID
}

func (q *Queries) UpdateMonitorStatus(ctx context.Context, arg UpdateMonitorStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMonitorStatus, arg.ID, arg.Enabled, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
