// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor_incidents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeMonitorIncident = `-- name: CloseMonitorIncident :one
UPDATE monitor_incidents
SET end_time = $2
WHERE monitor_id = $1 AND end_time IS NULL
RETURNING id
`

type CloseMonitorIncidentParams struct {
	MonitorID pgtype.UUID
	EndTime   pgtype.Timestamptz
}

func (q *Queries) CloseMonitorIncident(ctx context.Context, arg CloseMonitorIncidentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, closeMonitorIncident, arg.MonitorID, arg.EndTime)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMonitorIncident = `-- name: CreateMonitorIncident :one
INSERT INTO monitor_incidents (monitor_id, start_time, alerted, http_status, latency_ms)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateMonitorIncidentParams struct {
	MonitorID  pgtype.UUID
	StartTime  pgtype.Timestamptz
	Alerted    bool
	HttpStatus int32
	LatencyMs  int32
}

func (q *Queries) CreateMonitorIncident(ctx context.Context, arg CreateMonitorIncidentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMonitorIncident,
		arg.MonitorID,
		arg.StartTime,
		arg.Alerted,
		arg.HttpStatus,
		arg.LatencyMs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getIncidentByIDAndTeamID = `-- name: GetIncidentByIDAndTeamID :one
SELECT
    mi.id,
    mi.monitor_id,
    m.url AS monitor_url,
    mi.start_time,
    mi.end_time,
    mi.alerted,
    mi.http_status,
    mi.latency_ms,
    mi.created_at,
    (mi.end_time IS NULL)::BOOLEAN AS is_active,
    EXTRACT(EPOCH FROM (COALESCE(mi.end_time, now()) - mi.start_time))::BIGINT AS duration_sec,
    COALESCE(a.status, '') AS alert_status,
    COALESCE(a.alert_email, '') AS alert_email,
    a.sent_at AS alert_sent_at
FROM monitor_incidents mi
JOIN monitors m ON m.id = mi.monitor_id
LEFT JOIN LATERAL (
    SELECT status, alert_email, sent_at
    FROM alerts
    WHERE incident_id = mi.id
    ORDER BY created_at DESC
    LIMIT 1
) a ON true
WHERE mi.id = $1 AND m.team_id = $2
`

type GetIncidentByIDAndTeamIDParams struct {
	ID     pgtype.UUID
	TeamID pgtype.UUID
}

type GetIncidentByIDAndTeamIDRow struct {
	ID          pgtype.UUID
	MonitorID   pgtype.UUID
	MonitorUrl  string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Alerted     bool
	HttpStatus  int32
	LatencyMs   int32
	CreatedAt   pgtype.Timestamptz
	IsActive    bool
	DurationSec int64
	AlertStatus string
	AlertEmail  string
	AlertSentAt pgtype.Timestamptz
}

func (q *Queries) GetIncidentByIDAndTeamID(ctx context.Context, arg GetIncidentByIDAndTeamIDParams) (GetIncidentByIDAndTeamIDRow, error) {
	row := q.db.QueryRow(ctx, getIncidentByIDAndTeamID, arg.ID, arg.TeamID)
	var i GetIncidentByIDAndTeamIDRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.MonitorUrl,
		&i.StartTime,
		&i.EndTime,
		&i.Alerted,
		&i.HttpStatus,
		&i.LatencyMs,
		&i.CreatedAt,
		&i.IsActive,
		&i.DurationSec,
		&i.AlertStatus,
		&i.AlertEmail,
		&i.AlertSentAt,
	)
	return i, err
}

const getMonitorIncidentByID = `-- name: GetMonitorIncidentByID :one
SELECT id, monitor_id, start_time, end_time, alerted, http_status, latency_ms, created_at
FROM monitor_incidents
WHERE id = $1
`

func (q *Queries) GetMonitorIncidentByID(ctx context.Context, id pgtype.UUID) (MonitorIncident, error) {
	row := q.db.QueryRow(ctx, getMonitorIncidentByID, id)
	var i MonitorIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartTime,
		&i.EndTime,
		&i.Alerted,
		&i.HttpStatus,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const listIncidentsByTeamCursor = `-- name: ListIncidentsByTeamCursor :many
SELECT
    mi.id,
    mi.monitor_id,
    m.url AS monitor_url,
    mi.start_time,
    mi.end_time,
    mi.alerted,
    mi.http_status,
    mi.latency_ms,
    mi.created_at,
    (mi.end_time IS NULL)::BOOLEAN AS is_active,
    EXTRACT(EPOCH FROM (COALESCE(mi.end_time, now()) - mi.start_time))::BIGINT AS duration_sec,
    COALESCE(a.status, '') AS alert_status,
    COALESCE(a.alert_email, '') AS alert_email,
    a.sent_at AS alert_sent_at
FROM monitor_incidents mi
JOIN monitors m ON m.id = mi.monitor_id
LEFT JOIN LATERAL (
    SELECT status, alert_email, sent_at
    FROM alerts
    WHERE incident_id = mi.id
    ORDER BY created_at DESC
    LIMIT 1
) a ON true
WHERE m.team_id = $1
  AND (
    $2::text = 'all'
        OR ($2::text = 'active' AND mi.end_time IS NULL)
        OR ($2::text = 'resolved' AND mi.end_time IS NOT NULL)
    )
  AND ($3::timestamptz IS NULL OR mi.start_time >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR mi.start_time <= $4::timestamptz)
  AND ($5::text = '' OR m.url ILIKE ('%' || $5 || '%'))
  AND ($6::uuid IS NULL OR mi.monitor_id = $6::uuid)
  AND (
    $7::timestamptz IS NULL
        OR (mi.start_time, mi.id) < ($7::timestamptz, $8::uuid)
    )
ORDER BY mi.start_time DESC, mi.id DESC
LIMIT $9
`

type ListIncidentsByTeamCursorParams struct {
	TeamID  pgtype.UUID
	Column2 string
	Column3 pgtype.Timestamptz
	Column4 pgtype.Timestamptz
	Column5 string
	Column6 pgtype.UUID
	Column7 pgtype.Timestamptz
	Column8 pgtype.UUID
	Limit   int32
}

type ListIncidentsByTeamCursorRow struct {
	ID          pgtype.UUID
	MonitorID   pgtype.UUID
	MonitorUrl  string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Alerted     bool
	HttpStatus  int32
	LatencyMs   int32
	CreatedAt   pgtype.Timestamptz
	IsActive    bool
	DurationSec int64
	AlertStatus string
	AlertEmail  string
	AlertSentAt pgtype.Timestamptz
}

func (q *Queries) ListIncidentsByTeamCursor(ctx context.Context, arg ListIncidentsByTeamCursorParams) ([]ListIncidentsByTeamCursorRow, error) {
	rows, err := q.db.Query(ctx, listIncidentsByTeamCursor,
		arg.TeamID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsByTeamCursorRow
	for rows.Next() {
		var i ListIncidentsByTeamCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.MonitorUrl,
			&i.StartTime,
			&i.EndTime,
			&i.Alerted,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.CreatedAt,
			&i.IsActive,
			&i.DurationSec,
			&i.AlertStatus,
			&i.AlertEmail,
			&i.AlertSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
