// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlugin = `-- name: DeletePlugin :exec
DELETE FROM plugins
WHERE team_id = $1 AND plugin_type = $2
`

type DeletePluginParams struct {
	TeamID     pgtype.UUID
	PluginType string
}

func (q *Queries) DeletePlugin(ctx context.Context, arg DeletePluginParams) error {
	_, err := q.db.Exec(ctx, deletePlugin, arg.TeamID, arg.PluginType)
	return err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, team_id, plugin_type, enabled, config_enc, created_at, updated_at FROM plugins
WHERE team_id = $1 AND plugin_type = $2
`

type GetPluginParams struct {
	TeamID     pgtype.UUID
	PluginType string
}

func (q *Queries) GetPlugin(ctx context.Context, arg GetPluginParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, getPlugin, arg.TeamID, arg.PluginType)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PluginType,
		&i.Enabled,
		&i.ConfigEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, team_id, plugin_type, enabled, config_enc, created_at, updated_at FROM plugins
WHERE team_id = $1
ORDER BY plugin_type
`

func (q *Queries) ListPlugins(ctx context.Context, teamID pgtype.UUID) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listPlugins, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.PluginType,
			&i.Enabled,
			&i.ConfigEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlugin = `-- name: UpsertPlugin :one
INSERT INTO plugins (team_id, plugin_type, enabled, config_enc, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (team_id, plugin_type)
DO UPDATE SET
    enabled    = EXCLUDED.enabled,
    config_enc = EXCLUDED.config_enc,
    updated_at = now()
RETURNING id, team_id, plugin_type, enabled, config_enc, created_at, updated_at
`

type UpsertPluginParams struct {
	TeamID     pgtype.UUID
	PluginType string
	Enabled    bool
	ConfigEnc  string
}

func (q *Queries) UpsertPlugin(ctx context.Context, arg UpsertPluginParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, upsertPlugin,
		arg.TeamID,
		arg.PluginType,
		arg.Enabled,
		arg.ConfigEnc,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PluginType,
		&i.Enabled,
		&i.ConfigEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
