// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, is_active, joined_at
`

type AddTeamMemberParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT tm.id, tm.team_id, tm.user_id, tm.role, tm.is_active, tm.joined_at
FROM team_members tm
WHERE tm.team_id = $1 AND tm.user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.name, u.email, tm.role, tm.is_active, u.created_at
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY u.created_at ASC
`

type ListTeamMembersRow struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Role      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamMemberActive = `-- name: SetTeamMemberActive :exec
UPDATE team_members
SET is_active = $3
WHERE team_id = $1 AND user_id = $2
`

type SetTeamMemberActiveParams struct {
	TeamID   pgtype.UUID
	UserID   pgtype.UUID
	IsActive bool
}

func (q *Queries) SetTeamMemberActive(ctx context.Context, arg SetTeamMemberActiveParams) error {
	_, err := q.db.Exec(ctx, setTeamMemberActive, arg.TeamID, arg.UserID, arg.IsActive)
	return err
}

const userIsMember = `-- name: UserIsMember :one
SELECT EXISTS(
    SELECT 1 FROM team_members
    WHERE team_id = $1 AND user_id = $2
) AS is_member
`

type UserIsMemberParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UserIsMember(ctx context.Context, arg UserIsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, userIsMember, arg.TeamID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
