// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package db

import (
	"context"
)

const getTeam = `-- name: GetTeam :one
SELECT id, name FROM team WHERE id = 1
`

type GetTeamRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetTeam(ctx context.Context) (GetTeamRow, error) {
	row := q.db.QueryRow(ctx, getTeam)
	var i GetTeamRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateTeamName = `-- name: UpdateTeamName :exec
UPDATE team SET name = $1 WHERE id = 1
`

func (q *Queries) UpdateTeamName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, updateTeamName, name)
	return err
}
